name = "cf-rate-limiter"
main = "src/index.ts"
compatibility_date = "2023-06-26"

[durable_objects]
bindings = [
  { name = "limiter", class_name = "RateLimiter" }
]

[[migrations]]
tag = "v1"
new_classes = ["RateLimiter"]