name = "cf-rate-limiter"
main = "src/index.ts"
compatibility_date = "2023-06-26"

# Replace domain.com with your domain
routes = [{ pattern = "domain.com", custom_domain = true }]

[durable_objects]
bindings = [
  { name = "limiter", class_name = "RateLimiter" }
]

[[migrations]]
tag = "v1"
new_classes = ["RateLimiter"]